name: stack_wallet_backup
description: Create and restore secure encrypted backups using a passphrase.
version: 0.1.0
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  cryptography: ^2.0.5
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
